extends Node

signal joy_collected
signal player_died(position)
signal circle_shrink_finished
signal joy_attached_to_cape
signal float_started
signal float_ended
signal player_dashed
signal level_completed(level_index)
signal begin_cape_regrow